### ISSUE TITLE
Error running SHERM on my dataset.

### ISSUE THREAD

**Issue by jmlipman** [liu-yikang/SHERM#1]
Hello,

I'm trying to use SHERM on one of my images and I changed Demo.m to read nii.gz:

```
img_list = dir(fullfile(input_dir, '*.nii.gz'));
animal = {'rat'};
isotropic = [0];
```

But then, it gives me this error:

> Error using  < 
> Matrix dimensions must agree.
> 
> Error in sherm (line 42)
> [ids_chan, ids_mser] = find((desc_dist >0 & desc_dist) < (min(desc_dist(desc_dist>0)) + 0.05*sum(abs(desc_tmp))));

What is exactly that line and how could I fix it so that it works on my data?

Thanks.

**Comment by vgrouza** [comment]
I am also getting the same error.

**Comment by liu-yikang** [comment]
Hi. Thanks for using our tool. This line selects brain mask candidates that have shapes similar to the template, where the similarity, determined by the distance between its shape descriptor and the template's (desc_dist), is smaller than a threshold (min(desc_dist(desc_dist>0)) + 0.05*sum(abs(desc_tmp)). 

The error may be caused by min(desc_dist(desc_dist>0)) return more than one value.

**Comment by liu-yikang** [comment]
I think I corrected the error. Please try it on your data again. Thanks!

**Comment by vgrouza** [comment]
I think you actually just broke the code since you used square brackets (Pythonic) rather than round brackets (Matlab-ic).

**Comment by liu-yikang** [comment]
> I think you actually just broke the code since you used square brackets (Pythonic) rather than round brackets (Matlab-ic).

Yeah you are right. Thanks for pointing out. It's corrected. Code too much in Python recently lol
